module ApplicationHelper
	def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
	end

	def neighborhoods
    [
      ['5th Ave Park', '5th Ave Park'],
      ['Alphabet City', 'Alphabet City'],
      ['Chelsea', 'Chelsea'],
      ['Chinatown', 'Chinatown'],
      ['Columbus Circle', 'Columbus Circle'],
      ['East Village', 'East Village'],
      ['Faltiron', 'Faltiron'],
      ['Financial District', 'Financial District'],
      ['Gramercy', 'Gramercy'],
      ['Greenwich Village', 'Greenwich Village'],
      ['LES', 'LES'],
      ['Little Italy', 'Little Italy'],
      ['Madison Ave', 'Madison Ave'],
      ['Meatpacking', 'Meatpacking'],
      ['Midtown', 'Midtown'],
      ['Nolita', 'Nolita'],
      ['Soho', 'Soho'],
      ['TriBeCa', 'TriBeCa'],      
      ['Union Square', 'Union Square'],
      ['West Village', 'West Village'],           
      ['Williamsburg', 'Williamsburg'],
      ['Upper East', 'Upper East'],
      ['Upper West', 'Upper West'],      
    ]
	end
end
